name: Run Azure Login With a Service Principal Secret 

on: 
  push:

jobs:
  build-and-deploy:
    name: Deploy Terraform Infrastructure using GitHub CI/CD
    runs-on: windows-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Verify Azure Login Details
        shell: pwsh
        run: |
          az account show

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8  # Specify the required Terraform version

      - name: Change Directory to Terraform Code
        # Update the path if your Terraform code is in a subfolder
        run: cd ./terraform

      - name: List Directory Contents (Debug Step)
        shell: pwsh
        run: |
          Write-Host "Listing contents of the current directory:"
          Get-ChildItem

      - name: Verify Terraform Files
        shell: pwsh
        run: |
          if (!(Test-Path -Path ".\main.tf")) {
            Write-Host "Error: main.tf file not found in the current directory."
            exit 1
          }

      - name: Terraform Init
        id: init
        shell: pwsh
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        run: |
          terraform init `
            -backend-config="resource_group_name=${{ secrets.AZURE_RESOURCE_GROUP }}" `
            -backend-config="storage_account_name=${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}" `
            -backend-config="container_name=${{ secrets.AZURE_STORAGE_CONTAINER_NAME }}" `
            -backend-config="key=terraform.tfstate"

      # Run a terraform plan for pull requests only
      - name: Terraform Plan
        id: plan
        shell: pwsh
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        run: terraform plan -no-color

      - name: Terraform Apply
        shell: pwsh
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        run: terraform apply -auto-approve
