# File: .github/workflows/workflow.yml

on: [push]

name: Run Azure Login With a Service Principal Secret 

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show

  terraform:
    name: Deploy Terraform Infrastructure
    runs-on: ubuntu-latest

    env:
      ARM_ACCESS_KEY: ${{ secrets.AZURE_STORAGE_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.3  # Specify the required Terraform version

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          ARM_ACCESS_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
